### PR TITLE
Black pyproject toml

### PR DESCRIPTION
**Pull request by mimakaev**

### CODE REVIEW

**Comment by henr7110** [comment]
Did I get it right that you made no major structural changes apart from automated formatting, renaming variables, and rewriting some code to better use python (static type checks, defining functions rather than using lambda functions, etc.)?

**Comment by mimakaev** [comment]
correct. There are no major structural changes. It would be good to just run a couple of scripts you've used recently to make sure I didn't randomly break anything.

**Comment by kannandeepti** [comment]
- Ran scripts in `examples` to check that `black`, `isort`, and `flake8` did not break anything
- Fixed and renamed `polychrom/param_units.py`. @henr7110 it would be great if you could check this file as it is new. Basically just provides some discussion on how to interpret polychrom parameters through the lens of the Rouse model and provides some functions to calculate physically meaningful qualities (i.e. diffusion coefficient, Rouse time) from polychrom parameters.
- Added a ValueError in scripts in `examples/customIntegrators` to check that correct number of command line arguments are specified when running the scripts.

**Comment by henrik-dahl-pinholt** [comment]
@mimakaev I ran the library on a piece of code I'm using these days to simulate and everything ran fine. So I agree with @kannandeepti  that the whole thing works. 

@kannandeepti, regarding the `polychrom/param_units.py` I think it would make sense to emphasize that this is just one approach to starting simulations. Instead of writing it as a guidance for choosing parameters I think I would phrase it as a guidance for a guess at which initial parameters to use (as you do in the text but not in your function definitions). I make this distinction because the guesses that come out from Rouse need not be the ones that match all types of data best in which case further parameter fitting is needed anyhow. My (perhaps silly) fear is that people will think that this is how to get the best parameters for all types of chromatin simulations in general which is certainly not the case. I do however think it is a neat writeup that exemplifies some of the 'hidden' unit choices and definitely deserves to be in the library. 

One way to emphasize this would be to explicitly suggest how the assumptions for your functions could break down and how bad/good the approximation then is. For example, one may be simulating a topology-conserving chain in which case your function `get_D_from_measured_Dapp` would yield erroneous results as this would have dynamics as MSD~t^0.4.

**Comment by kannandeepti** [comment]
> 

Good points! Fixed the docstring of the `SimulationParams` class and the `get_D_from_measured_Dapp` function to clarify these points. In general, the class does not really help you guess or choose simulation parameters. It's just a way of computing some physical quantities from the polychrom parameters assuming a Rouse model. Let me know if the docs clarify!

**Comment by henrik-dahl-pinholt** [comment]
I like the new suggestions and think this is ready to go! Will accept when checks have completed

**Pull request merged**
